### ISSUE TITLE
Spicy-plugin creates dangling links (assuming binary installation)

### ISSUE THREAD

**Issue by 0xxon** [zeek/spicy-plugin#119]
An installation of spicy-plugin will leave the following dangling link in `include/zeek/builtin-plugins/spicy-plugin/lib64`:

```
[johanna@johanna-zeek-compile lib64]$ ls -lh
total 1.0K
lrwxrwxrwx 1 johanna johanna 57 Jun 15 09:57 zeek-spicy -> /home/johanna/zeek/build/src/builtin-plugins/spicy-plugin
```

Assuming a binary installation, this link will point into nothingness; having links to outside of the distribution directory also violates packaging guidelines on just about any system, and generally seems like a bad idea.

@bbannier pointed me to this as the cause https://github.com/zeek/spicy-plugin/blob/8cd9a0b9f38f130422f821966a3e865e59e8c036/CMakeLists.txt#L211-L216 and mentioned that there might have been a discussion between @sethhall and @rsmmr about this.

I am not sure what the reason for this is - but in my opinion we should not have links back into the source folder in a finished installation.

Optimally this should be removed for the 5.0 release.

**Comment by rsmmr** [comment]
I don't quite recall the context here, but I'll take a look.

**Comment by rsmmr** [comment]
@0xxon ☝️

**Comment by rsmmr** [comment]
I still don't see a `lib64` link at all, tried it on Ubuntu. I'll try F36 next.

```
# ./configure --binary-package --enable-static-broker --enable-static-binpac --disable-broker-tests --build-type=Release --prefix=/home/robin/tmp/install --generator=Ninja --build-dir=build-ubuntu
# cd build-ubuntu
# ninja install
# ls -al $HOME/tmp/install/include/zeek/builtin-plugins/spicy-plugin
total 48
drwxr-xr-x 9 robin robin 4096 Jun 24 09:50 .
drwxr-xr-x 3 robin robin 4096 Jun 24 09:50 ..
drwxr-xr-x 2 robin robin 4096 Jun 24 09:50 bin
drwxr-xr-x 2 robin robin 4096 Jun 24 09:50 cmake
-rw-r--r-- 1 robin robin 1579 Jun 23 13:32 consts.bif.h
-rw-r--r-- 1 robin robin  820 Jun 23 13:32 events.bif.h
-rw-r--r-- 1 robin robin  696 Jun 23 13:32 functions.bif.h
drwxr-xr-x 3 robin robin 4096 Jun 24 09:50 include
drwxr-xr-x 2 robin robin 4096 Jun 24 09:50 lib
drwxr-xr-x 2 robin robin 4096 Jun 24 09:50 spicy
drwxr-xr-x 3 robin robin 4096 Jun 24 09:50 src
drwxr-xr-x 3 robin robin 4096 Jun 24 09:50 tests
```

**Comment by rsmmr** [comment]
> Well, on ubuntu the same broken link is in the `lib` subdirectory, instead of `lib64` :)

I actually didn't see any link even with that configure, not sure why. Either way, looks like Benjamin found a solution.

**Comment by 0xxon** [comment]
Great, thank you.
Out of curiosity - this only removes the symlinks in binary packaging mode. Which means that for most people that do source installations, they will still be present - even if the source-tree is removed later. Why are the links needed at all?
