### ISSUE TITLE
Packet analyzers misname the Zeek-side tag

### ISSUE THREAD

**Issue by rsmmr** [zeek/spicy-plugin#130]
Given a packet analyzer defined like this:

```
packet analyzer spicy::MyAnalyzer:
    parse with MyAnalyzer::MyPacket;
```

The plugin creates a Zeek-side tag for this that comes with an additional underscore for some reason:

```
# zeek -NN Zeek::Spicy
...
    [Packet Analyzer] spicy::MyAnalyzer (ANALYZER_SPICY__MYANALYZER)
...
```

It should be `ANALYZER_SPICY_MYANALYZER` instead. Other types of analyzers don't do this.

**Comment by simeonmiteff** [comment]
Yup, this has been bugging me!
