### ISSUE TITLE
Installed Zeek has side-effects on testing in-tree

### ISSUE THREAD

**Issue by ckreibich** [zeek/spicy-plugin#134]
I'm not sure this is the right place to flag this, but here goes: when I install a specific version of Zeek into my system so that its `bin` folder is in `PATH`, this seems to affect Zeek's spicy-related testing, causing test failures.

Specifically, when I have a Zeek 5.1 build installed and test latest Zeek `master`, I see these:
```
[ 99%] spicy.spicyz-aot ... failed
[ 99%] spicy.spicyz-jit ... failed
```
There's a clue in the `.stderr` output of the first test:
```
/home/christian/devel/zeek/zeek/build/src/builtin-plugins/spicy-plugin/include/zeek-spicy/zeek-compat.h:21:2: error: #error "Mismatch in Zeek version numbers"
   21 | #error "Mismatch in Zeek version numbers"
      |  ^~~~~
/home/christian/devel/zeek/zeek/build/src/builtin-plugins/spicy-plugin/include/zeek-spicy/zeek-compat.h:20:96: note: '#pragma message: Zeek version 50200 vs 50100)'
   20 | #pragma message "Zeek version " STR(ZEEK_SPICY_VERSION_NUMBER) " vs " STR(ZEEK_VERSION_NUMBER) ")"
```
When I remove my installed tree and re-run the tests in my local build, they succeed.

**Comment by rsmmr** [comment]
This should be fixed.
