### ISSUE TITLE
Provide an easier way to use a certain Spicy branch in CI

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy-plugin#169]
We currently install Spicy from a deb file in CI. This is fast and works well, but makes it pretty much impossible to test against a certain Spicy branch. Possible fixes:

1. Allow some magic variable `SPICY_BRANCH`. If it is set we build and install Spicy from that branch instead of using deb files. This should work but can be slow.
2. Figure out a way to get CI artifacts for a certain Spicy branch. Cirrus does not directly expose this, but it should be possible to get this information from the GH API (via test suite statuses) and the Cirrus API.

**Comment by rsmmr** [comment]
> 2. Figure out a way to get CI artifacts for a certain Spicy branch. Cirrus does not directly expose this, but it should be possible to get this information from the GH API (via test suite statuses) and the Cirrus API.

Note, we aren't even building `docker_debian11` for Spicy branches right now (the platform that spicy-plugin's CI wants to download).
