### ISSUE TITLE
Automatic Zeek type creation clashes with using common base libraries

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy-plugin#177]
Probably unsurprising, if one adds the same Spicy source file to multiple HLTO files, one cannot use these HLTO files at the same time since the same types on the Zeek side are declared multiple times (from multiple HLTO files). This is bad since it makes it hard to reuse identical helper types and functions in multiple modules (e.g., imagine a world where multiple independent parsers pull in ASN1 parsers for subparser).

At least for my tests this only seems to happen for modules directly added to the `spicyz` invocation like one would do for proper dependency tracking in e.g., a CMake setup; if one instead simply imports and uses the module there seems to be no issue.

We should figure out why there is a mismatch between simply imported and explicitly added modules, and also check whether we need to reject all such duplicate definitions (tricky bit: even if only looking at types generated from the Spicy side, it probably is hard to decide whether identical names indeed refer to identical types).

Reproducer in the Zeek repo (e.g., `testing/btest/spicy/spicyz-common.spicy`), zeek/zeek@39f0b780436cf711c8d084bd486cf188e259e892:

```ruby
# Works.
# @TEST-EXEC: ${BUILD}/src/builtin-plugins/spicy-plugin/bin/spicyz -o a.hlto a.spicy
# @TEST-EXEC: ${BUILD}/src/builtin-plugins/spicy-plugin/bin/spicyz -o b.hlto b.spicy
# @TEST-EXEC: zeek a.hlto b.hlto

# Breaks.
# @TEST-EXEC: ${BUILD}/src/builtin-plugins/spicy-plugin/bin/spicyz -o a.hlto a.spicy common.spicy
# @TEST-EXEC: ${BUILD}/src/builtin-plugins/spicy-plugin/bin/spicyz -o b.hlto b.spicy common.spicy
# @TEST-EXEC: zeek a.hlto b.hlto

# @TEST-START-FILE common.spicy
module common;

public type E = enum {
	X,
	Y,
};
# @TEST-END-FILE

# @TEST-START-FILE a.spicy
module a;

import common;
global x: common::E;
# @TEST-END-FILE

# @TEST-START-FILE b.spicy
module b;

import common;
global x: common::E;
# @TEST-END-FILE
```

```console
$ btest -dv picy/spicyz-common.spicy
spicy.spicyz-common ...
  > ${BUILD}/src/builtin-plugins/spicy-plugin/bin/spicyz -o a.hlto a.spicy
  > ${BUILD}/src/builtin-plugins/spicy-plugin/bin/spicyz -o b.hlto b.spicy
  > zeek a.hlto b.hlto
  > ${BUILD}/src/builtin-plugins/spicy-plugin/bin/spicyz -o a.hlto a.spicy common.spicy
  > ${BUILD}/src/builtin-plugins/spicy-plugin/bin/spicyz -o b.hlto b.spicy common.spicy
  > zeek a.hlto b.hlto
... spicy.spicyz-common failed
  % 'zeek a.hlto b.hlto' failed unexpectedly (exit code 1)
  % cat .stderr
  error: attempt to overwrite already defined Zeek type 'common::E'

1 of 1 test failed
```

**Comment by rsmmr** [comment]
The new error checking might be just too strict here. The comes from when module initialization code runs, which doesn't happen for purely imported modules. I believe we should be able to determine if the two types are identical, and if so, ignore the duplicate registration. Will look more closely.
