### ISSUE TITLE
The installation of spicy-plugin always reports an error

### ISSUE THREAD

**Issue by KarenrY** [zeek/spicy-plugin#218]
Ubuntu 20.04
zeek version 5.0.9

The installation of spicy-plugin always reports an error, and the error message is as follows:

zkg install zeek/spicy-plugin

The following packages will be INSTALLED:
  zeek/zeek/spicy-plugin (v1.5.3)

Proceed? [Y/n] y
Running unit tests for "zeek/zeek/spicy-plugin"
error: failed to run tests for zeek/zeek/spicy-plugin: test_command failed with exit code 1
Proceed to install anyway? [N/y] y
Installing "zeek/zeek/spicy-plugin".......................................................................................................................................................................Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/miniconda3/envs/myconda/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/zeek/bin/zkg", line 481, in run
    self.error = self.manager.install(
  File "/opt/zeek/lib/zeek/python/zeekpkg/manager.py", line 2694, in install
    return self._install(matches[0], version)
  File "/opt/zeek/lib/zeek/python/zeekpkg/manager.py", line 2768, in _install
    fail_msg = self._stage(package, version, clone, stage)
  File "/opt/zeek/lib/zeek/python/zeekpkg/manager.py", line 2624, in _stage
    make_symlink(full_path, os.path.join(
  File "/opt/zeek/lib/zeek/python/zeekpkg/_util.py", line 66, in make_symlink
    raise error
  File "/opt/zeek/lib/zeek/python/zeekpkg/_util.py", line 60, in make_symlink
    os.symlink(target_path, link_path)
FileExistsError: [Errno 17] File exists: '/opt/zeek/var/lib/zkg/clones/package/spicy-plugin/build/bin/spicyz' -> '/opt/zeek/bin/spicyz'

Traceback (most recent call last):
  File "/opt/zeek/bin/zkg", line 2770, in <module>
    main()
  File "/opt/zeek/bin/zkg", line 2767, in main
    args.run_cmd(manager, args, config, configfile)
  File "/opt/zeek/bin/zkg", line 746, in cmd_install
    print('Installed "{}" ({})'.format(name, ipkg.status.current_version))
AttributeError: 'NoneType' object has no attribute 'status'

![zkg install spicy-plugin](https://github.com/zeek/spicy-plugin/assets/94332620/6af26d3a-f5ec-464e-b7fe-dd7f3e708a0b)

**Comment by bbannier** [comment]
There already is some installation of spicy-plugin on your system. Where does `/opt/zeek/bin/spicyz` come from? There are very likely more files from that installation, and the best approach would probably to bootstrap this machine again. If you installed a Zeek version which Spicy included (default setup since zeek-5.0.0) there is no need to install spicy-plugin or Spicy.

**Comment by KarenrY** [comment]
After completing the installation of zeek (version 5.0.9), there is spicyz in the bin directory. Will this affect my use of zkg to install spicy-plugin?

![zeekbin](https://github.com/zeek/spicy-plugin/assets/94332620/62c6aa46-e05f-4068-b768-66a625df5bee)
