### ISSUE TITLE
ghc::filesystem::canonical throws exceptions which spicy-plugin doesn't catch

### ISSUE THREAD

**Issue by sethhall** [zeek/spicy-plugin#47]
According to cppreference, filesystem::canonical used in the way referenced below throws exceptions.  If you would like the version that doesn't throw exceptions you must pass a reference to a std::error_code object.
    https://en.cppreference.com/w/cpp/filesystem/canonical

https://github.com/zeek/spicy-plugin/blob/906b38fea80fe3c92156e15b7897e4a1fb816b30/compiler/driver.cc#L83

**Comment by rsmmr** [comment]
The underlying problem seems to be that `plugin_path` can't reliably determined when compiled as a static plugin inside Zeek. We'll need to find a way around that.

**Comment by sethhall** [comment]
But that still doesn't address the core of this ticket does it?  That's only the reason that the unhandled exception is happening, but I suppose you would still want to use the method correctly according to the standard?
