### ISSUE TITLE
Provide primitives so that Spicy analyzers can forward data to other Zeek analyzers for follow-up analysis

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy-plugin#76]
We provide functions to pass data extracted by Spicy file analyzers back into Zeek with e.g.,
```.zeek
function zeek::file_begin(mime_type: optional<string> = Null) : string
```

Such functionality currently does not exist for Spicy protocol or packet analyzers. We should provide similar functions for such analyzers, ideally with some optional type so callers can opt into a specific analyzer to process the data (e.g., for HTTP with websockets can detect that the unparsed data is websockets) if they do not want Zeek to detect the format dynamically.

**Comment by rsmmr** [comment]
For packet analyzers, we have `forward_packet`. That's not quite the same (because it forward the current packet, rather than allowing to pass in arbitrary data), but I think that should do it for most use cases.
