### ISSUE TITLE
spicy-plugin can e.g., segfault if underlying Spicy breaks ABI

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy-plugin#82]
Currently `spicy-plugin` has a ABI dependency on the underlying Spicy installation so that e.g., upgrading Spicy without reinstalling `spicy-plugin` can lead to errors like segfaults.

It would be nice if it was clearer that the environment was broken. When debugging issues right now we often need to tell users to reinstall `spicy-plugin` to be sure which doesn't seem viable for the long term.

We should check whether we could either only use a "stable" Spicy ABI, or alternatively add a new layer in `spicy-plugin` which can catch ABI.

**Comment by rsmmr** [comment]
#147 now enforces matching versions, so this should be taken care of.
