### ISSUE TITLE
Use of `protocol_*` functions in corelight/zeek-spicy-openvpn triggers sigabort

### ISSUE THREAD

**Issue by bbannier** [zeek/spicy-plugin#92]
As of corelight/zeek-spicy-openvpn@6bcb4ec6dd3c8814cbb5186e688585b7bf105f97 the test suite of that analyzer fails on their Linux CI. The logs mention that many tests failed due to `SIGABRT`. This seems to coincide with them starting to use `protocol_*` functions from this package. 

We should look into this and depending on what we find either fix our implementation, or reject incorrect usage patterns.

This is also tracked in corelight/zeek-spicy-openvpn#3.

**Comment by rsmmr** [comment]
So I've tracked this down pretty far. The error is this at startup:

```
# zeek ...
[libhilti] Fatal error: could not open library path "/opt/zeek/lib/zeek/plugins/packages/spicy-analyzers/http.hlto": failed to load library "/opt/zeek/lib/zeek/plugins/packages/spicy-analyzers/http.hlto": /opt/zeek/lib/zeek/plugins/packages/spicy-analyzers/http.hlto: undefined symbol: _ZN5spicy4zeek2rt13file_set_sizeERK7SafeIntImN5hilti2rt7integer6detail16SafeIntExceptionEE

# echo _ZN5spicy4zeek2rt13file_set_sizeERK7SafeIntImN5hilti2rt7integer6detail16SafeIntExceptionEE | c++filt
spicy::zeek::rt::file_set_size(SafeInt<unsigned long, hilti::rt::integer::detail::SafeIntException> const&)
```

`_Zeek-Spicy.linux-x86_64.so` offers this instead:

```
spicy::zeek::rt::file_set_size(SafeInt<unsigned long, hilti::rt::integer::detail::SafeIntException> const&, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&)
```

What I don't understand yet is where this mixup comes from. For some reason, after building things like the GitHub action in the OpenVPN analyzer repo specifies, I end up with this:

```
# grep -R file_set_size /opt/zeek/ |grep runtime-support.h
/opt/zeek/lib/zeek/plugins/packages/spicy-plugin/include/zeek-spicy/runtime-support.h:void file_set_size(const hilti::rt::integer::safe<uint64_t>& size, const std::optional<std::string>& fid = {});
/opt/zeek/var/lib/zkg/clones/package/spicy-plugin/include/runtime-support.h:void file_set_size(const hilti::rt::integer::safe<uint64_t>& size, const std::optional<std::string>& fid = {});
/opt/zeek/var/lib/zkg/clones/package/spicy-plugin/build/include/zeek-spicy/runtime-support.h:void file_set_size(const hilti::rt::integer::safe<uint64_t>& size, const std::optional<std::string>& fid = {});
/opt/zeek/var/lib/zkg/scratch/spicy-plugin/include/runtime-support.h:void file_set_size(const hilti::rt::integer::safe<uint64_t>& size, const std::optional<std::string>& fid = {});
/opt/zeek/var/lib/zkg/testing/spicy-plugin/clones/spicy-plugin/build/include/zeek-spicy/runtime-support.h:void file_set_size(const hilti::rt::integer::safe<uint64_t>& size);
/opt/zeek/var/lib/zkg/testing/spicy-plugin/clones/spicy-plugin/include/runtime-support.h:void file_set_size(const hilti::rt::integer::safe<uint64_t>& size);
/opt/zeek/var/lib/zkg/testing/spicy-plugin/plugins/packages/spicy-plugin/include/zeek-spicy/runtime-support.h:void file_set_size(const hilti::rt::integer::safe<uint64_t>& size);
```

Looks like the OpenVPN analyzer is then built against the header file from `testing/`. I'm not sure right now why, and where that is even coming from.

I'll stop here for now.

**Comment by rsmmr** [comment]
Ok, looks like the Docker image comes with an old version of the plugin. With a fresh container:

```
# zkg list
zeek/zeek/spicy-analyzers (installed: main)
zeek/zeek/spicy-plugin (installed: main)

# /opt/zeek/lib/zeek/plugins/packages/spicy-plugin/bin/spicyz --version
1.3.0
```

@bbannier can you take a look at what's going on there?

Also: On the Docker image, `spicyz` is not in `PATH`.

**Comment by bbannier** [comment]
> Ok, looks like the Docker image comes with an old version of the plugin. With a fresh container:
> 
> ```
> # zkg list
> zeek/zeek/spicy-analyzers (installed: main)
> zeek/zeek/spicy-plugin (installed: main)
> 
> # /opt/zeek/lib/zeek/plugins/packages/spicy-plugin/bin/spicyz --version
> 1.3.0
> ```
> 
> @bbannier can you take a look at what's going on there?
> 
> Also: On the Docker image, `spicyz` is not in `PATH`.

I believe this is a red herring we already looked into. The CI job for corelight/zeek-spicy-openvpn uses the image for the last release, i.e., currently `zeekurity/spicy:1.3.0`. That image contains the version of `zeek/spicy-plugin` which was most recent at the time of the spicy-1.3.0 release, i.e., `spicy-plugin-1.3.0`. The CI job then however upgrades spicy-plugin to the latest release, i.e., `spicy-plugin-1.3.6`.

There is also `zeekurity/spicy-dev` which currently contains `spicy-plugin-1.3.6` (and also has `spicyz` in the default `PATH`). The problem reproduces there as well.

```.console
$ docker run -it zeekurity/spicy-dev

# Inside container.
$ git clone https://github.com/corelight/zeek-spicy-openvpn.git

$ mkdir zeek-spicy-openvpn/build
$ cd zeek-spicy-openvpn/build

$ cmake ..
$ make

$ cd ../tests
$ btest -dv btest -dv analyzer/openvpn.zeek
analyzer.openvpn ...
  > zeek -C -r ${TRACES}/openvpn.pcap %INPUT >openvpn.out
... analyzer.openvpn failed
  % 'zeek -C -r ${TRACES}/openvpn.pcap /root/zeek-spicy-openvpn/tests/.tmp/analyzer.openvpn/openvpn.zeek >openvpn.out' failed unexpectedly (exit code 139)
  % cat .stderr
  Segmentation fault (core dumped)

1 of 1 test failed
```

**Comment by rsmmr** [comment]
Alright, that was total red herring indeed. (I had actually followed what the CI does, including the upgrade, but whatever).

With spicy-dev I can now reproduce it, but it took a Zeek debug version to understand what's going on:

```
zeek: /root/zeek/src/analyzer/protocol/ssl/SSL.cc:60: virtual void zeek::analyzer::ssl::SSL_Analyzer::DeliverStream(int, const u_char*, bool): Assertion `TCP()' failed.
```

We're forwarding data from a UDP session to a TCP-based analyzer, which Zeek's SSL analyzer doesn't like. This will be tricky, and potentially impossible, to fix without a Zeek change ...
